# Generated by Django 5.2.1 on 2025-05-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Nothing', max_length=100),
            preserve_default=False,
        ),
    ]
