# Generated by Django 5.2.1 on 2025-06-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopInfo',
            fields=[
                ('cam_ung', models.IntegerField(blank=True, null=True)),
                ('height_mm', models.FloatField(blank=True, null=True)),
                ('url_path', models.CharField(blank=True, max_length=128, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_max_support', models.FloatField(blank=True, null=True)),
                ('storage_gb', models.FloatField(blank=True, null=True)),
                ('display_width', models.FloatField(blank=True, null=True)),
                ('bluetooth_version', models.FloatField(blank=True, null=True)),
                ('width_mm', models.FloatField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_max_speed', models.FloatField(blank=True, null=True)),
                ('root_price', models.FloatField(blank=True, null=True)),
                ('cpu_threads', models.FloatField(blank=True, null=True)),
                ('cpu_cores', models.FloatField(blank=True, null=True)),
                ('ram_speed', models.FloatField(blank=True, null=True)),
                ('product_weight', models.FloatField(blank=True, null=True)),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('ram_type', models.CharField(blank=True, max_length=50, null=True)),
                ('refresh_rate', models.FloatField(blank=True, null=True)),
                ('cpu_speed', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('ram_storage', models.FloatField(blank=True, null=True)),
                ('is_installment', models.IntegerField(blank=True, null=True)),
                ('ram_slots', models.FloatField(blank=True, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_capacity', models.FloatField(blank=True, null=True)),
                ('laptop_color', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=50, null=True)),
                ('vga_type', models.CharField(blank=True, max_length=50, null=True)),
                ('depth_mm', models.FloatField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
                ('vga_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('product_id', models.CharField(db_column='product_id', max_length=50, primary_key=True, serialize=False)),
                ('cpu_series', models.CharField(blank=True, max_length=50, null=True)),
                ('display_height', models.FloatField(blank=True, null=True)),
                ('vga_vram', models.FloatField(blank=True, null=True)),
                ('laptop_camera', models.CharField(blank=True, max_length=50, null=True)),
                ('display_size', models.FloatField(blank=True, null=True)),
                ('cpu_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('hoc_tap_van_phong', models.IntegerField(blank=True, null=True)),
                ('laptop_sang_tao_noi_dung', models.IntegerField(blank=True, null=True)),
                ('mong_nhe', models.IntegerField(blank=True, null=True)),
                ('gaming', models.IntegerField(blank=True, null=True)),
                ('do_hoa_ky_thuat', models.IntegerField(blank=True, null=True)),
                ('cao_cap_sang_trong', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laptop_info',
                'managed': False,
            },
        ),
    ]
